services:
  r34app:
    build: .
    container_name: r34app
    ports:
      - "3000:3000"
    environment:
      API_KEY: ${API_KEY}
      USER_ID: ${USER_ID}
      DB_PATH: /app/data/r34-browser.sqlite
    volumes:
      - ./data:/app/data
    restart: unless-stopped